openapi: '3.0.3'

info:
  title: 'GRIND API'
  version: '0.0.2'

tags:
  - name: 'Auth'
    description: 'Authentication'

  - name: 'Invite Code'
    description: 'Invite code management'

  - name: 'User'
    description: 'User management'

  - name: 'Event'
    description: 'Events management'

paths:
  /auth/telegram:
    post:
      tags: [Auth]
      summary: 'Authenticate via Telegram'
      parameters:
        - $ref: '#/components/parameters/TelegramInitData'
      requestBody:
        $ref: '#/components/requestBodies/TelegramAuth'
      responses:
        '200':
          $ref: '#/components/responses/TelegramAuth'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'

  /invite-codes:
    post:
      tags: ['Invite Code']
      summary: 'Invite code creation'
      parameters:
        - $ref: '#/components/parameters/JWTAuthToken'
      requestBody:
        $ref: '#/components/requestBodies/CreateInviteCode'
      responses:
        '200':
          $ref: '#/components/responses/EmptySuccess'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
      security:
        - Bearer: []

  /users/me/invite-codes:
    get:
      tags: [User]
      summary: 'Invite codes of authorized user'
      parameters:
        - $ref: '#/components/parameters/JWTAuthToken'
      responses:
        '200':
          $ref: '#/components/responses/GetInviteCodes'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
      security:
        - Bearer: []

  /users/me/profile:
    get:
      tags: [User]
      summary: 'Get profile of authorized user'
      parameters:
        - $ref: '#/components/parameters/JWTAuthToken'
      responses:
        '200':
          $ref: '#/components/responses/GetUserProfile'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
      security:
        - Bearer: []

  /users/me/skills:
    get:
      tags: [User]
      summary: 'Get skills of authorized user'
      parameters:
        - $ref: '#/components/parameters/JWTAuthToken'
      responses:
        '200':
          $ref: '#/components/responses/GetUserSkills'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
      security:
        - Bearer: []

  /events:
    post:
      tags: [Event]
      summary: 'Create event'
      parameters:
        - $ref: '#/components/parameters/JWTAuthToken'
      requestBody:
        $ref: '#/components/requestBodies/CreateEvent'
      responses:
        '200':
          $ref: '#/components/responses/EmptySuccess'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
      security:
        - Bearer: []

  /users/me/events:
    get:
      tags: [User]
      summary: 'Get events of authorized user'
      parameters:
        - $ref: '#/components/parameters/JWTAuthToken'
      responses:
        '200':
          $ref: '#/components/responses/GetUserEvents'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
      security:
        - Bearer: []

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    TelegramInitData:
      name: Authorization
      in: header
      required: true
      schema: { type: string }
      example: 'tma xxxxxxxxxxx'

    JWTAuthToken:
      name: Authorization
      in: header
      required: true
      schema: { type: string }
      example: 'Bearer xxxxxxxxxxx'

  schemas:
    SuccessResponse:
      type: object
      properties:
        data:
          nullable: true

    PaginationResponse:
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
        - properties:
            data:
              type: object
              properties:
                current_page: { type: integer }
                next_page: { type: integer }
                limit: { type: integer }
                items:
                  type: array
                  items:
                    nullable: true

    ErrorsResponse:
      type: object
      properties:
        errors:
          type: object
          additionalProperties: { type: string }

    UUID:
      type: string
      format: uuid

    DateTime:
      type: string
      format: datetime

    URL:
      type: string
      format: uri

    BaseInviteCode:
      type: object
      properties:
        code: { type: string }
        max_uses: { type: integer }

    InviteCodeListItem:
      allOf:
        - $ref: '#/components/schemas/BaseInviteCode'
        - properties:
            id: { $ref: '#/components/schemas/UUID' }
            uses: { type: integer }
            created_at: { $ref: '#/components/schemas/DateTime' }

    User:
      type: object
      properties:
        id: { $ref: '#/components/schemas/UUID' }
        telegram_id: { type: integer }
        nickname: { type: string }
        avatar_url: { $ref: '#/components/schemas/URL' }
        created_at: { $ref: '#/components/schemas/DateTime' }

    UserProfile:
      allOf:
        - $ref: '#/components/schemas/User'
        - properties:
            inviter: { $ref: '#/components/schemas/User' }

    Skill:
      type: object
      properties:
        id: { $ref: '#/components/schemas/UUID' }
        title: { type: string }
        total_xp: { type: integer }
        level: { type: integer }
        start_of_current_level_xp: { type: integer }
        xp_to_next_level: { type: integer }

    EventReward:
      type: object
      properties:
        skill_id: { $ref: '#/components/schemas/UUID' }
        xp: { type: integer }

    EventListItem:
      type: object
      properties:
        id: { $ref: '#/components/schemas/UUID' }
        title: { type: string }
        source: { type: string }
        rewards:
          type: array
          items:
            $ref: '#/components/schemas/EventReward'
        created_at: { $ref: '#/components/schemas/DateTime' }

    TelegramAuthRequestBody:
      type: object
      properties:
        invite_code: { type: string }

    TelegramAuthResponse:
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
        - properties:
            data:
              type: object
              properties:
                token: { type: string }

    CreateInviteCodeRequestBody:
      $ref: '#/components/schemas/BaseInviteCode'

    GetInviteCodesResponse:
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
        - properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/InviteCodeListItem'

    GetUserProfileResponse:
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
        - properties:
            data:
              $ref: '#/components/schemas/UserProfile'

    GetUserSkillsResponse:
      allOf:
        - $ref: '#/components/schemas/SuccessResponse'
        - properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/Skill'

    CreateEventRequestBody:
      type: object
      properties:
        title: { type: string }

    GetUserEventsResponse:
      allOf:
        - $ref: '#/components/schemas/PaginationResponse'
        - properties:
            data:
              type: object
              properties:
                items:
                  type: array
                  items:
                    $ref: '#/components/schemas/EventListItem'

  examples:
    EmptySuccessResponse:
      value:
        data: []

    BadRequestResponse:
      value:
        errors:
          other: 'Something went wrong'

    UnauthorizedResponse:
      value:
        errors:
          other: 'Unauthorized'

    ForbiddenResponse:
      value:
        errors:
          other: 'Forbidden'

    NotFoundResponse:
      value:
        errors:
          other: 'Not found'

    UnprocessableEntityResponse:
      value:
        errors:
          field1: 'field1 is required'
          field2: 'field2 has invalid format'
          field3: 'field3 must be numeric'

    TooManyRequestsResponse:
      value:
        errors:
          other: 'Too many requests'

    TelegramAuthRequestBody:
      value:
        invite_code: 'INVITE12345'

    TelegramAuthResponse:
      value:
        data:
          token: 'xxxxxxxxxxxxxxxxxxxxxxx'

    CreateInviteCodeRequestBody:
      value:
        code: 'INVITE12345'
        max_uses: 5

    GetInviteCodesResponse:
      value:
        data:
          - id: '550e8400-e29b-41d4-a716-446655440000'
            code: 'INVITE12345'
            uses: 2
            max_uses: 5
            created_at: '2024-01-01T12:00:00Z'
          - id: '550e8400-e29b-41d4-a716-446655440001'
            code: 'INVITE67890'
            uses: 0
            max_uses: 3
            created_at: '2024-01-02T15:30:00Z'

    GetUserProfileResponse:
      value:
        data:
          id: '550e8400-e29b-41d4-a716-446655440002'
          telegram_id: 10000323233
          nickname: 'UF2xx'
          avatar_url: 'https://example.com/avatar.jpg'
          created_at: '2024-01-02T15:30:00Z'
          inviter:
            id: '550e8400-e29b-41d4-a716-446655440003'
            telegram_id: 10000543532
            nickname: 'sunsetsavorer'
            avatar_url: 'https://example.com/inviter_avatar.jpg'
            created_at: '2024-01-02T15:30:00Z'

    GetUserSkillsResponse:
      value:
        data:
          - id: '550e8400-e29b-41d4-a716-446655440004'
            title: 'Endurance'
            total_xp: 1500
            level: 3
            start_of_current_level_xp: 1000
            xp_to_next_level: 2000
          - id: '550e8400-e29b-41d4-a716-446655440005'
            title: 'Power'
            total_xp: 500
            level: 2
            start_of_current_level_xp: 300
            xp_to_next_level: 800

    CreateEventRequestBody:
      value:
        title: 'Do 10 pushups'

    GetUserEventsResponse:
      value:
        data:
          current_page: 1
          next_page: 2
          limit: 10
          items:
            - id: '550e8400-e29b-41d4-a716-446655440006'
              title: 'Do 10 pushups'
              source: 'manually'
              rewards:
                - skill_id: '550e8400-e29b-41d4-a716-446655440004'
                  xp: 100
              created_at: '2024-01-03T08:00:00Z'
            - id: '550e8400-e29b-41d4-a716-446655440007'
              title: 'Run 5 kilometers'
              source: 'manually'
              rewards:
                - skill_id: '550e8400-e29b-41d4-a716-446655440004'
                  xp: 300
                - skill_id: '550e8400-e29b-41d4-a716-446655440005'
                  xp: 150
              created_at: '2024-01-04T10:30:00Z'
            - id: '550e8400-e29b-41d4-a716-446655440008'
              title: 'Swim 1 kilometer'
              source: 'manually'
              rewards:
                - skill_id: '550e8400-e29b-41d4-a716-446655440004'
                  xp: 500
              created_at: '2024-01-05T14:45:00Z'

  requestBodies:
    TelegramAuth:
      description: 'Request body for Telegram authentication'
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TelegramAuthRequestBody'
          examples:
            base:
              $ref: '#/components/examples/TelegramAuthRequestBody'

    CreateInviteCode:
      description: 'Request body for creating invite code'
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateInviteCodeRequestBody'
          examples:
            base:
              $ref: '#/components/examples/CreateInviteCodeRequestBody'

    CreateEvent:
      description: 'Request body for creating event'
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateEventRequestBody'
          examples:
            base:
              $ref: '#/components/examples/CreateEventRequestBody'

  responses:
    EmptySuccess:
      description: 'Success response'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SuccessResponse'
          examples:
            success:
              $ref: '#/components/examples/EmptySuccessResponse'

    BadRequest:
      description: 'Something went wrong'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorsResponse'
          examples:
            error:
              $ref: '#/components/examples/BadRequestResponse'

    Unauthorized:
      description: 'Unauthorized'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorsResponse'
          examples:
            error:
              $ref: '#/components/examples/UnauthorizedResponse'

    Forbidden:
      description: 'Forbidden'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorsResponse'
          examples:
            error:
              $ref: '#/components/examples/ForbiddenResponse'

    NotFound:
      description: 'Not found'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorsResponse'
          examples:
            error:
              $ref: '#/components/examples/NotFoundResponse'

    UnprocessableEntity:
      description: 'Validation error'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorsResponse'
          examples:
            error:
              $ref: '#/components/examples/UnprocessableEntityResponse'

    TooManyRequests:
      description: 'Too many request'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorsResponse'
          examples:
            error:
              $ref: '#/components/examples/TooManyRequestsResponse'

    TelegramAuth:
      description: 'Response for Telegram authentication'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TelegramAuthResponse'
          examples:
            success:
              $ref: '#/components/examples/TelegramAuthResponse'

    GetInviteCodes:
      description: 'Response for getting invite codes of authorized user'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetInviteCodesResponse'
          examples:
            success:
              $ref: '#/components/examples/GetInviteCodesResponse'

    GetUserProfile:
      description: 'Response for getting profile of authorized user'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetUserProfileResponse'
          examples:
            success:
              $ref: '#/components/examples/GetUserProfileResponse'

    GetUserSkills:
      description: 'Response for getting skills of authorized user'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetUserSkillsResponse'
          examples:
            success:
              $ref: '#/components/examples/GetUserSkillsResponse'

    GetUserEvents:
      description: 'Response for getting events of authorized user'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetUserEventsResponse'
          examples:
            success:
              $ref: '#/components/examples/GetUserEventsResponse'